'use client';
import {usePathname} from 'next/navigation';
import {useEffect,useState} from 'react';
import {Menu} from 'lucide-react';
export const WHITEPAPER='/whitepaper';
export const links=[['Platform','/platform'],['Use cases','/use-cases'],['Developers','/developers'],['Directory','/directory'],['Trust','/trust']];
export function Mark(){return <svg aria-hidden="true" viewBox="24 24 212 212"><g fill="none" stroke="currentColor" strokeWidth="23" strokeLinejoin="miter" strokeLinecap="square"><path d="M105 36 H36 V105"/><path d="M155 36 H224 V105"/><path d="M36 155 V224 H105"/><path d="M155 224 H224 V155"/><path d="M95 130 H165"/></g></svg>}
export function Brand(){return <a href="/" className="brand" aria-label="ARKHAI home"><Mark/><span>ARKHAI</span></a>}
function Navigation({pathname}:{pathname:string}){return <>{links.map(([name,url])=><a key={url} href={url} aria-current={pathname===url?'page':undefined}>{name}</a>)}<a href={WHITEPAPER} aria-current={pathname===WHITEPAPER?'page':undefined}>Whitepaper</a><a className="button small" href="/explore">Explore ARKHAI <span className="button-dot"/></a></>}
export function Shell({children}:{children:React.ReactNode}){
 const pathname=usePathname();
 useEffect(()=>{const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('[data-reveal]').forEach(e=>obs.observe(e));return()=>obs.disconnect()},[pathname]);
 return <><a className="skip-link" href="#main-content">Skip to content</a><header className="header"><Brand/><nav className="nav desktop-nav" aria-label="Main navigation"><Navigation pathname={pathname}/></nav><details className="mobile-menu"><summary aria-label="Toggle navigation"><Menu aria-hidden="true" size={26}/><span className="sr-only">Menu</span></summary><nav className="nav" aria-label="Mobile navigation"><Navigation pathname={pathname}/></nav></details></header><main id="main-content" tabIndex={-1}>{children}</main><footer><div className="footer-top"><p className="eyebrow">A PERMANENT PLACE TO PICK UP THE THREAD.</p><a href="/explore" className="footer-cta">LET’S TALK.</a><div className="footer-meta"><span>Persistent email addresses.<br/>Continuous correspondence.</span><div>{links.map(([name,url])=><a key={url} href={url}>{name}</a>)}<a href={WHITEPAPER}>Whitepaper</a></div></div></div><div className="footer-bottom"><Brand/><span className="mono">© {new Date().getFullYear()} ARKHAI</span><span className="mono">SAME EMAIL ADDRESS. NEXT CHAPTER.</span></div></footer></>;
}
export function CopyButton({text,label='Copy'}:{text:string,label?:string}){const [status,setStatus]=useState('');return <><button className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText(text);setStatus('Copied')}catch{setStatus('Copy unavailable. Select and copy the text.')}setTimeout(()=>setStatus(''),3000)}}>{label}</button><span className="copy-status" role="status">{status}</span></>}
export function PageIntro({number,kicker,title,children}:{number:string;kicker:string;title:React.ReactNode;children:React.ReactNode}){return <section className="page-intro"><div className="eyebrow"><span>{number} / {kicker}</span><span>ARKHAI FIELD NOTES</span></div><h1>{title}</h1><div className="intro-description">{children}</div></section>}
