'use client';
import {useEffect,useRef,useState} from 'react';
import {X} from 'lucide-react';
export function useTransactionNotice(){
 const [action,setAction]=useState('');const dialog=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!action)return;const previous=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.querySelector<HTMLButtonElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setAction('');if(e.key==='Tab'){const buttons=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button,a')||[]);if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===buttons.at(-1)){e.preventDefault();buttons[0]?.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);previous?.focus()}},[action]);
 const detail=action==='Send message'||action==='Send structured message'?'Message delivery is coming soon. Your message has not been sent.':(action==='Register agent email address'||action==='Register agent address')?'Agent email registration is coming soon. Your email address has not been registered.':action==='Upload attachment'?'File uploads are coming soon. No file has been uploaded.':action==='Submit purchase'?'Purchase transactions are coming soon. No purchase order has been submitted.':'Workflow transactions are coming soon. No approval or workflow change has been submitted.';
 const notice=action?<div className="modal-backdrop transaction-backdrop" onClick={e=>{if(e.target===e.currentTarget)setAction('')}}><div ref={dialog} className="modal" role="dialog" aria-modal="true" aria-labelledby="transaction-title"><button className="close" aria-label="Close notice" onClick={()=>setAction('')}><X/></button><span className="eyebrow">{action}</span><h2 id="transaction-title">COMING<br/><em>SOON.</em></h2><p role="status">This is a demo workspace. {detail}</p><button className="button" onClick={()=>setAction('')}>Back to workspace <span className="button-dot"/></button></div></div>:null;
 return {attempt:setAction,notice};
}
