export type Scenario='procurement'|'support'|'research'|'approval';
export type Stage='draft'|'waiting'|'quotes'|'review'|'approved'|'rejected'|'expired'|'complete';
export type Message={id:string;thread:string;sender:string;content:string;time:number;system?:boolean};
export type Event={id:string;type:string;reason:string;time:number;thread:string;messageId?:string;idempotency:string;retryable?:boolean};
export type State={version:1;scenario:Scenario;stage:Stage;clock:number;messages:Message[];events:Event[];quote:number;proposalVersion:number;approval:{proposalVersion:number;quote:number;role:string;expires:number}|null;replyRound:number;counter:number};
export type Action={type:'start'}|{type:'advance';hours:number}|{type:'select';quote:number}|{type:'request'}|{type:'decide';role:string;decision:'approve'|'reject'}|{type:'complete'}|{type:'message';sender:string;recipient:string;content:string;idempotency?:string;threadId?:string}|{type:'retry';eventId:string}|{type:'fail'}|{type:'policy';sender:string;messageType:string;action:string};
export const suppliers=[{id:'atlas',name:'Atlas',price:2400,days:5},{id:'northstar',name:'Northstar',price:2180,days:7},{id:'meridian',name:'Meridian',price:2650,days:3}];
export const baseTime=Date.parse('2026-10-03T09:00:00Z');
export const iso=(hours:number)=>new Date(baseTime+hours*3600000).toISOString();
export const timeLabel=(hours:number)=>new Date(baseTime+hours*3600000).toLocaleString('en-GB',{timeZone:'UTC',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false})+' UTC';
export function initial(scenario:Scenario='procurement'):State{return {version:1,scenario,stage:'draft',clock:0,messages:[],events:[],quote:0,proposalVersion:1,approval:null,replyRound:0,counter:0}}
function clone(s:State):State{return {...s,messages:[...s.messages],events:[...s.events],approval:s.approval?{...s.approval}:null}}
function event(s:State,type:string,reason:string,thread='workflow',extra:Partial<Event>={}){const id='evt-'+(++s.counter);s.events.push({id,type,reason,time:s.clock,thread,idempotency:id,...extra})}
function message(s:State,thread:string,sender:string,content:string,system=false,id?:string){const mid=id||'msg-'+(++s.counter);if(s.messages.some(m=>m.id===mid))return;s.messages.push({id:mid,thread,sender,content,time:s.clock,system});event(s,'message.received','Message retained in '+thread,thread,{messageId:mid})}
export function reduce(state:State,action:Action):State{const s=clone(state);
 if(action.type==='start'){if(s.stage!=='draft')return state;s.stage=s.scenario==='approval'?'quotes':'waiting';message(s,'workflow','System',s.scenario==='procurement'?'Purchase request: 20 USB-C desk kits for the operations team. Budget: $2,500 including delivery.':s.scenario==='support'?'Support request SUP-1042: webhook delivery returns HTTP 401 after a signing-key rotation.':s.scenario==='research'?'Research brief RES-028: compare direct HTTP, event queues and a hybrid approach for supplier coordination.':'Proposed action: publish the reviewed research summary.',true);if(s.scenario==='procurement'){suppliers.forEach(p=>message(s,p.id,'procurement@company.arkhai','Please quote 20 USB-C desk kits: one dock, keyboard and mouse per kit. Include delivery to our office, lead time and total price in USD.'))}else if(s.scenario!=='approval'){message(s,s.scenario,'you@company.arkhai',s.scenario==='support'?'Webhook deliveries began returning HTTP 401 after we rotated the signing key at 08:40 UTC. The endpoint is reachable. Please review the authorization settings.':'Compare direct HTTP, event queues and a hybrid approach for supplier replies that can arrive several hours apart. Include retry behavior, context retention and approval handling.');event(s,'route.matched','Priority '+(s.scenario==='support'?30:20)+' matched. Routed to '+s.scenario+' specialist.',s.scenario)}else{event(s,'proposal.staged','Current proposal is ready for review.')}return s}
 if(action.type==='advance'){if(!Number.isFinite(action.hours)||action.hours<=0||action.hours>168)return state;s.clock+=action.hours;event(s,'clock.advanced','Response window: '+action.hours+' hours.');if(s.stage==='waiting'){if(s.scenario==='procurement'){const count=Math.min(3,Math.floor(s.clock/3));for(let i=s.replyRound;i<count;i++){const p=suppliers[i];message(s,p.id,'quotes@'+p.id+'.arkhai',`20 USB-C desk kits at $${(p.price/20).toFixed(2)} each. Total: $${p.price.toLocaleString()}, delivery included. Lead time: ${p.days} days. Quote valid for 7 days.`)}s.replyRound=count;if(count===3){s.stage='quotes';message(s,'workflow','System','All three quotes have arrived in their original threads. Select a proposal for review.',true)}}else{message(s,s.scenario,s.scenario+'@company.arkhai',s.scenario==='support'?'The endpoint is reachable and the request body is valid. Update the receiver to use the current signing key, redeploy its configuration, then retry the failed delivery with the original event ID. Keep the previous key during the rotation window.':'Recommendation: use an event queue for supplier replies and direct HTTP for short lookups. Store thread IDs with each event, deduplicate retries by event ID, and bind finance approval to the exact proposal version. Direct HTTP alone needs separate timeout and retry handling for delayed replies.');s.stage='quotes';s.replyRound=1}}if((s.stage==='review'||s.stage==='approved')&&s.approval&&s.clock>=s.approval.expires){s.stage='expired';event(s,'approval.expired','Deadline passed. Continuation is blocked.','finance');message(s,'finance','System','The approval window expired. A new review is required.',true)}return s}
 if(action.type==='select'){if(!Number.isInteger(action.quote)||action.quote<0||action.quote>2||!['quotes','review','approved','rejected','expired'].includes(s.stage)||s.scenario!=='procurement')return state;if(s.quote===action.quote)return state;s.quote=action.quote;s.proposalVersion++;s.approval=null;s.stage='quotes';event(s,'proposal.changed','Earlier approval invalidated. Version '+s.proposalVersion+' requires a new decision.');return s}
 if(action.type==='request'){if(!['quotes','rejected','expired'].includes(s.stage)||!['procurement','approval'].includes(s.scenario))return state;s.stage='review';s.approval={proposalVersion:s.proposalVersion,quote:s.quote,role:'finance',expires:s.clock+24};message(s,'finance',s.scenario==='approval'?'research@company.arkhai':'procurement@company.arkhai',s.scenario==='procurement'?`Please approve ${suppliers[s.quote].name}: 20 USB-C desk kits, $${suppliers[s.quote].price.toLocaleString()} including delivery, ${suppliers[s.quote].days}-day lead time. Proposal v${s.proposalVersion}. Review due in 24 hours.`:`Please approve publication of the reviewed summary. Proposal v${s.proposalVersion}.`);event(s,'approval.requested','Bound to action '+s.scenario+'-01 and proposal v'+s.proposalVersion,'finance');return s}
 if(action.type==='decide'){if(s.stage!=='review'||!s.approval)return state;if(action.role!=='finance'){event(s,'permission.denied','Role '+action.role+' cannot approve this action.','finance');return s}if(s.approval.expires<=s.clock||s.approval.proposalVersion!==s.proposalVersion||s.approval.quote!==s.quote){event(s,'approval.invalid','Approval is expired or no longer matches this proposal.','finance');return s}s.stage=action.decision==='approve'?'approved':'rejected';message(s,'finance','finance@company.arkhai',action.decision==='approve'?'Approved the current proposal. You may continue.':'Rejected the current proposal. Do not continue.');event(s,'approval.'+s.stage,'Finance decision on proposal v'+s.proposalVersion,'finance');return s}
 if(action.type==='complete'){if(s.scenario==='support'||s.scenario==='research'){if(s.stage!=='quotes')return state}else if(s.stage!=='approved'||!s.approval||s.approval.expires<=s.clock||s.approval.proposalVersion!==s.proposalVersion||s.approval.quote!==s.quote)return state;s.stage='complete';message(s,'workflow','System','Local workflow completed. No external action was executed.',true);event(s,'workflow.completed','Completed once. Thread history retained.');return s}
 if(action.type==='message'){if(!action.content.trim()||action.content.length>5000)return state;const known=['workflow','finance','research','support','procurement','operations',...suppliers.map(p=>p.id)];if(!known.includes(action.recipient)){event(s,'delivery.undeliverable','Unknown recipient. Choose an address from the directory.',action.recipient);return s}message(s,action.threadId||action.recipient,action.sender,action.content.trim(),false,action.idempotency);if(s.stage==='expired')event(s,'reply.late','Late message retained; expired action remains blocked.',action.recipient);return s}
 if(action.type==='policy'){const r=evaluateRoute(action.sender,action.messageType,action.action);event(s,r.allowed?'policy.permitted':'permission.denied',r.id+' → '+r.destination+'. '+r.reason,'policy');return s}
 if(action.type==='fail'){if(s.events.some(e=>e.idempotency==='retry-fixture-01'))return state;event(s,'delivery.failed','Temporary delivery failure. Eligible for retry.','workflow',{retryable:true,idempotency:'retry-fixture-01',messageId:'retry-message-01'});return s}
 if(action.type==='retry'){const e=s.events.find(e=>e.id===action.eventId);if(!e?.retryable)return state;message(s,e.thread,'System','Retried delivery received once.',true,e.messageId);s.events=s.events.map(x=>x.id===e.id?{...x,retryable:false}:x);event(s,'delivery.retried','Retry uses the same idempotency identifier.',e.thread,{idempotency:e.idempotency,messageId:e.messageId});return s}return state}
export function evaluateRoute(sender:string,type:string,action:string){const rule=type==='approval.request'?{id:'R10',destination:'finance@company.arkhai',priority:10}:type==='research.request'?{id:'R20',destination:'research@company.arkhai',priority:20}:type==='support.request'?{id:'R30',destination:'support@company.arkhai',priority:30}:{id:'DEFAULT',destination:'review',priority:999};const allowed=action==='conversation'||sender==='finance';return {...rule,allowed,verified:sender!=='unknown',reason:allowed?(action==='conversation'?'Conversation may be received. This grants no execution authority.':'The finance role is authorized to approve this action.'):'Only the finance role may approve this action.'}}
export function validateAddress(handle:string,namespace:string){const part=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;if(!part.test(handle)||!part.test(namespace))return {error:'Use lowercase letters, digits and internal hyphens. Both fields are required.'};const address=handle+'@'+namespace+'.arkhai';if(['research@company.arkhai','procurement@company.arkhai','finance@company.arkhai','support@company.arkhai','operations@company.arkhai','quotes@atlas.arkhai'].includes(address))return {error:'This address already exists in the directory.'};return {address}}
export function validatePayload(text:string){try{const p=JSON.parse(text);if(!p||Array.isArray(p)||typeof p!=='object')return {error:'Expected a JSON object.'};for(const key of ['sender','recipient','threadId','type','content']){if(typeof p[key]!=='string'||!p[key].trim())return {error:`${key} must be a non-empty string.`}}return {payload:p as Record<string,string>}}catch{return {error:'Malformed JSON. Check quotes, commas and braces.'}}}
export function restore(raw:string):State{const s=JSON.parse(raw);if(s?.version!==1||!['procurement','support','research','approval'].includes(s.scenario)||!['draft','waiting','quotes','review','approved','rejected','expired','complete'].includes(s.stage)||!Number.isFinite(s.clock)||!Number.isInteger(s.counter)||!Number.isInteger(s.proposalVersion)||!Number.isInteger(s.replyRound)||!Number.isInteger(s.quote)||s.quote<0||s.quote>2||!Array.isArray(s.messages)||!Array.isArray(s.events)||s.messages.length>500||s.events.length>1000)throw Error('Incompatible session');for(const m of s.messages)if(!['id','thread','sender','content'].every(k=>typeof m[k]==='string')||!Number.isFinite(m.time))throw Error('Invalid message');for(const e of s.events)if(!['id','type','reason','thread','idempotency'].every(k=>typeof e[k]==='string')||!Number.isFinite(e.time))throw Error('Invalid event');if(s.approval&&(!Number.isInteger(s.approval.proposalVersion)||!Number.isInteger(s.approval.quote)||typeof s.approval.role!=='string'||!Number.isFinite(s.approval.expires)))throw Error('Invalid approval');return s}
